DATASETS:
  CONFIG:
    NAME: BEHAVE-Extend
    ROOT_DIR: /storage/data/huochf/BEHAVE
    DO_FLIP: True
    EXTREME_CROP_AUG_RATE: -1.
    SMPL_DEPTH_MEAN: 2.36
SMPL:
  MODEL_PATH: prohmr_custom/ProHMR/data/smpl
  GENDER: neutral
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_EXTRA: ./externals/prohmr_custom/ProHMR/data/SMPL_to_J19.pkl
  MEAN_PARAMS: ./externals/prohmr_custom/ProHMR/data/smpl_mean_params.npz
GENERAL:
  TOTAL_STEPS: 50000000
  LOG_STEPS: 100
  VAL_STEPS: 100
  CHECKPOINT_STEPS: 10000
  NUM_WORKERS: 4
TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 64
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 2
  NUM_TEST_SAMPLES: 64
  POSE_2D_NOISE_RATIO: 0.01
  SMPL_PARAM_NOISE_RATIO: 0.005
LOSS_WEIGHTS:
  KEYPOINTS_3D_EXP: 0.0
  KEYPOINTS_3D_MODE: 0.05
  KEYPOINTS_2D_EXP: 0.001
  KEYPOINTS_2D_MODE: 0.01
  GLOBAL_ORIENT_EXP: 0.000
  GLOBAL_ORIENT_MODE: 0.001
  BODY_POSE_EXP: 0.0
  BODY_POSE_MODE: 0.001
  ORTHOGONAL: 0.1
  BETAS_EXP: 0.0
  BETAS_MODE: 0.0005
  NLL: 0.001
  ADVERSARIAL: 0.0005
  CAM_T: 0.1
MODEL:
  IMAGE_SIZE: 224
  IMAGE_MEAN: [0.485, 0.456, 0.406]
  IMAGE_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    TYPE: resnet
    NUM_LAYERS: 50
    OUT_CHANNELS: 2048
  FLOW:
    DIM: 144
    NUM_LAYERS: 4
    CONTEXT_FEATURES: 2048
    LAYER_HIDDEN_FEATURES: 1024
    LAYER_DEPTH: 2
  FC_HEAD:
    NUM_FEATURES: 1024
EXTRA:
  FOCAL_LENGTH: 5000
  NUM_LOG_IMAGES: 4
  NUM_LOG_SAMPLES_PER_IMAGE: 8
  PELVIS_IND: 39
